import {
  BookOpen,
  Film,
  Github,
  Globe,
  MessageCircle,
  Newspaper,
  Search,
  Tv,
  Twitter,
  Video,
  Zap,
  Users,
  Code,
  Radio,
  Book,
  SearchIcon,
  Gamepad2,
  CloudLightning,
  History,
  Flame,
  NewspaperIcon,
  Bookmark,
  Coffee,
  Laptop,
  Rss,
  FileCode,
  Lightbulb,
  Rocket,
  PenTool,
  Layers,
} from "lucide-react"

// 平台分类
export const categories = {
  social: {
    id: "social",
    name: "社交媒体",
    icon: Users,
    description: "社交平台热门话题",
  },
  tech: {
    id: "tech",
    name: "科技开发",
    icon: Code,
    description: "科技与开发者社区热点",
  },
  entertainment: {
    id: "entertainment",
    name: "娱乐影音",
    icon: Radio,
    description: "视频、音乐与影视热点",
  },
  reading: {
    id: "reading",
    name: "新闻阅读",
    icon: Book,
    description: "新闻与阅读平台热点",
  },
  search: {
    id: "search",
    name: "搜索平台",
    icon: SearchIcon,
    description: "搜索引擎热搜榜单",
  },
  game: {
    id: "game",
    name: "游戏",
    icon: Gamepad2,
    description: "游戏相关热点",
  },
  info: {
    id: "info",
    name: "资讯服务",
    icon: CloudLightning,
    description: "天气、地震等资讯",
  },
}

// This maps our config keys to the actual API endpoint names
export const platformApiMapping: Record<string, string> = {
  github: "hellogithub",
  "36kr": "36kr",
  weibo: "weibo",
  zhihu: "zhihu",
  "zhihu-daily": "zhihu-daily",
  baidu: "baidu",
  tieba: "tieba",
  douyin: "douyin",
  bilibili: "bilibili",
  sspai: "sspai",
  ithome: "ithome",
  "ithome-xijiayi": "ithome-xijiayi",
  juejin: "juejin",
  "douban-movie": "douban-movie",
  "douban-group": "douban-group",
  "netease-news": "netease-news",
  weread: "weread",
  "51cto": "51cto",
  acfun: "acfun",
  coolapk: "coolapk",
  csdn: "csdn",
  earthquake: "earthquake",
  genshin: "genshin",
  history: "history",
  honkai: "honkai",
  hupu: "hupu",
  huxiu: "huxiu",
  ifanr: "ifanr",
  jianshu: "jianshu",
  lol: "lol",
  ngabbs: "ngabbs",
  nodeseek: "nodeseek",
  "qq-news": "qq-news",
  sina: "sina",
  "sina-news": "sina-news",
  starrail: "starrail",
  thepaper: "thepaper",
  toutiao: "toutiao",
  v2ex: "v2ex",
  weatheralarm: "weatheralarm",
}

export const platformConfig = {
  weibo: {
    title: "微博",
    description: "中国最大的社交媒体平台",
    icon: Twitter,
    category: "social",
  },
  zhihu: {
    title: "知乎",
    description: "中文互联网高质量的问答社区",
    icon: MessageCircle,
    category: "social",
  },
  "zhihu-daily": {
    title: "知乎日报",
    description: "知乎每日精选内容",
    icon: Bookmark,
    category: "reading",
  },
  baidu: {
    title: "百度",
    description: "中国最大的搜索引擎",
    icon: Search,
    category: "search",
  },
  tieba: {
    title: "百度贴吧",
    description: "中国最大的社区论坛",
    icon: MessageCircle,
    category: "social",
  },
  douyin: {
    title: "抖音",
    description: "中国最流行的短视频平台",
    icon: Video,
    category: "social",
  },
  bilibili: {
    title: "哔哩哔哩",
    description: "中国年轻人喜爱的视频平台",
    icon: Tv,
    category: "entertainment",
  },
  "36kr": {
    title: "36氪",
    description: "中国领先的科技媒体",
    icon: Zap,
    category: "tech",
  },
  sspai: {
    title: "少数派",
    description: "高品质数字消费指南",
    icon: Globe,
    category: "reading",
  },
  ithome: {
    title: "IT之家",
    description: "科技新闻和评测平台",
    icon: Laptop,
    category: "tech",
  },
  "ithome-xijiayi": {
    title: "IT之家-喜加一",
    description: "IT之家西贾亦频道",
    icon: Lightbulb,
    category: "tech",
  },
  github: {
    title: "Hello GitHub",
    description: "开发者关注的开源项目",
    icon: Github,
    category: "tech",
  },
  juejin: {
    title: "掘金",
    description: "开发者社区",
    icon: FileCode,
    category: "tech",
  },
  "douban-movie": {
    title: "豆瓣电影",
    description: "电影评分和讨论",
    icon: Film,
    category: "entertainment",
  },
  "douban-group": {
    title: "豆瓣小组",
    description: "豆瓣兴趣小组热门话题",
    icon: Users,
    category: "social",
  },
  "netease-news": {
    title: "网易新闻",
    description: "综合新闻平台",
    icon: Newspaper,
    category: "reading",
  },
  weread: {
    title: "微信读书",
    description: "流行电子书阅读平台",
    icon: BookOpen,
    category: "reading",
  },
  "51cto": {
    title: "51CTO",
    description: "IT技术社区",
    icon: Code,
    category: "tech",
  },
  acfun: {
    title: "AcFun",
    description: "弹幕视频网站",
    icon: Tv,
    category: "entertainment",
  },
  coolapk: {
    title: "酷安",
    description: "科技数码社区",
    icon: Smartphone,
    category: "tech",
  },
  csdn: {
    title: "CSDN",
    description: "程序员技术社区",
    icon: Code,
    category: "tech",
  },
  earthquake: {
    title: "地震速报",
    description: "全球地震信息",
    icon: Activity,
    category: "info",
  },
  genshin: {
    title: "原神",
    description: "原神游戏热点",
    icon: Gamepad2,
    category: "game",
  },
  history: {
    title: "历史上的今天",
    description: "历史事件回顾",
    icon: History,
    category: "info",
  },
  honkai: {
    title: "崩坏3",
    description: "崩坏3游戏热点",
    icon: Gamepad2,
    category: "game",
  },
  hupu: {
    title: "虎扑",
    description: "体育社区",
    icon: Flame,
    category: "social",
  },
  huxiu: {
    title: "虎嗅",
    description: "商业科技媒体",
    icon: Lightbulb,
    category: "tech",
  },
  ifanr: {
    title: "爱范儿",
    description: "科技生活媒体",
    icon: Layers,
    category: "tech",
  },
  jianshu: {
    title: "简书",
    description: "创作社区",
    icon: PenTool,
    category: "reading",
  },
  lol: {
    title: "英雄联盟",
    description: "英雄联盟游戏热点",
    icon: Gamepad2,
    category: "game",
  },
  ngabbs: {
    title: "NGA论坛",
    description: "游戏论坛",
    icon: MessageCircle,
    category: "game",
  },
  nodeseek: {
    title: "NodeSeek",
    description: "技术社区",
    icon: Code,
    category: "tech",
  },
  "qq-news": {
    title: "腾讯新闻",
    description: "综合新闻平台",
    icon: NewspaperIcon,
    category: "reading",
  },
  sina: {
    title: "新浪网",
    description: "综合门户网站",
    icon: Globe,
    category: "social",
  },
  "sina-news": {
    title: "新浪新闻",
    description: "新闻资讯平台",
    icon: NewspaperIcon,
    category: "reading",
  },
  starrail: {
    title: "崩坏：星穹铁道",
    description: "星穹铁道游戏热点",
    icon: Rocket,
    category: "game",
  },
  thepaper: {
    title: "澎湃新闻",
    description: "时政与思想类新闻",
    icon: NewspaperIcon,
    category: "reading",
  },
  toutiao: {
    title: "今日头条",
    description: "个性化推荐的资讯平台",
    icon: Rss,
    category: "reading",
  },
  v2ex: {
    title: "V2EX",
    description: "创意工作者社区",
    icon: Coffee,
    category: "tech",
  },
  weatheralarm: {
    title: "天气预警",
    description: "全国天气预警信息",
    icon: CloudLightning,
    category: "info",
  },
}

// 导入缺失的图标
import { Smartphone, Activity } from "lucide-react"
